image: node

include:
  template: Jobs/SAST.gitlab-ci.yml


pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - export NODE_OPTIONS=--openssl-legacy-provider; npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main